In [1]:
import pandas as pd
import numpy as np
import os

In [109]:
# mkdir ${KSI_DATA_ROOT}/processed_count_table

### blib_fp
1. The count table was generated using an empty subtrate library file, and so should be further sanitized

In [127]:
DATADIR = "${KSI_DATA_ROOT}/sequencing_data_1217/02_fastp_out/"
filename = 'blib_fp.count.txt'
dat = pd.read_csv(os.path.join(DATADIR,filename),sep = '\t')

In [128]:
dat_filtered = dat.loc[dat['sgRNA'].apply(lambda s: len(s.split('GGGAGGTGGAGCTAGC'))>1),:]

In [129]:
dat_filtered = dat_filtered.loc[dat_filtered['sgRNA'].apply(lambda s: len(s.split('TGGATCAGGTGGTTAGAAGCTTATTAGTT'))>1),:]

In [130]:
dat_filtered['sgRNA_trimmed'] = dat_filtered['sgRNA'].apply(lambda s: s.split('GGGAGGTGGAGCTAGC')[1].split('GGTGGATCAGGTGGTTAGAAGCTTATTAGTT')[0])

In [131]:
dat_filtered.loc[dat_filtered['sgRNA_trimmed'].apply(lambda s: len(s)==45)].shape[0]/dat_filtered.shape[0]

0.9155959190990727

In [132]:
dat_filtered = dat_filtered.loc[dat_filtered['sgRNA_trimmed'].apply(lambda s: len(s)==45)]
dat_filtered['Gene'] = dat_filtered['sgRNA_trimmed'].apply(lambda s: str(Seq(s).translate()))

In [133]:
dat_filtered.head(5)

,sgRNA,Gene,blib10_mtx,blib10_pre,blib7_mtx,blib7_pre,sgRNA_trimmed
76,GGGAGGTGGAGCTAGCAACTTGGCTTCTAGTCATACTTATGATAAT...,NLASSHTYDNFHSNS,31599,28746,1,0,AACTTGGCTTCTAGTCATACTTATGATAATTTTCACTCCAATTCA
77,GGGAGGTGGAGCTAGCTTGCCACAAGATAAAGAGTACTATAAGGTT...,LPQDKEYYKVKEPGE,13056,9456,0,0,TTGCCACAAGATAAAGAGTACTATAAGGTTAAAGAACCTGGTGAA
78,GGGAGGTGGAGCTAGCATTTCTGGAACTCAACCAGTTTATCATCAA...,ISGTQPVYHQGEHYQ,15064,12289,0,0,ATTTCTGGAACTCAACCAGTTTATCATCAAGGTGAACACTACCAG
79,GGGAGGTGGAGCTAGCGATTATGGAATGATGTCTGACTACGGTACA...,DYGMMSDYGTARRTG,6651,11224,4,0,GATTATGGAATGATGTCTGACTACGGTACAGCTAGAAGGACTGGC
80,GGGAGGTGGAGCTAGCCAGGAAGAAGAGGATGACGATTACCCAGGT...,QEEEDDDYPGSYSPQ,50360,18122,5,2,CAGGAAGAAGAGGATGACGATTACCCAGGTTCATATTCTCCTCAA

In [134]:
dat_filtered.to_csv('${KSI_DATA_ROOT}/processed_count_table/blib_fp.count.txt',sep = '\t',index = False)

In [239]:
dat_filtered = pd.read_csv('${KSI_DATA_ROOT}/processed_count_table/blib_fp.count.txt',sep = '\t')
dat_filtered_sub = dat_filtered.loc[:,['sgRNA','Gene','blib10_pre','blib10_mtx']]
dat_filtered_sub = dat_filtered_sub.loc[dat_filtered_sub.iloc[:,2]+dat_filtered_sub.iloc[:,3]>100,:]
print(dat_filtered_sub.shape) 
dat_filtered_sub.to_csv('${KSI_DATA_ROOT}/processed_count_table/blib_fpblib10.count.txt',sep = '\t',index = False)

(2808, 4)

In [240]:
dat_filtered = pd.read_csv('${KSI_DATA_ROOT}/processed_count_table/blib_fp.count.txt',sep = '\t')
dat_filtered_sub = dat_filtered.loc[:,['sgRNA','Gene','blib7_pre','blib7_mtx']]
dat_filtered_sub = dat_filtered_sub.loc[dat_filtered_sub.iloc[:,2]+dat_filtered_sub.iloc[:,3]>100,:]
print(dat_filtered_sub.shape) 
dat_filtered_sub.to_csv('${KSI_DATA_ROOT}/processed_count_table/blib_fpblib7.count.txt',sep = '\t',index = False)

(3238, 4)

### QC on fp library coverage

In [12]:
ref_st = pd.read_csv("${KSI_DATA_ROOT}/substrates_st_230313.csv",sep = ",")

In [13]:
ref_st['Insert Sequence'] = ref_st['Insert Sequence'].apply(lambda s : s.split('AGGAGGGTCAGGTGGTGGCGGCTCGGGAGGTGGAGCTAGC')[1])

In [14]:
ref_st['Insert Sequence'] = ref_st['Insert Sequence'].apply(lambda s : s.split('GGTGGATCAGGTGGTGGTGGTTCTGGTGGC')[0])

In [15]:
ref_st['Insert Sequence'].isin(dat_filtered['sgRNA_trimmed']).sum()/ref_st['Insert Sequence'].shape[0]

0.9883720930232558

In [16]:
ref_y = pd.read_csv("${KSI_DATA_ROOT}/substrates_y_230313.csv",sep = ",")

ref_y['Insert Sequence'] = ref_y['Insert Sequence'].apply(lambda s : s.split('AGGAGGGTCAGGTGGTGGCGGCTCGGGAGGTGGAGCTAGC')[1])

ref_y['Insert Sequence'] = ref_y['Insert Sequence'].apply(lambda s : s.split('GGTGGATCAGGTGGTGGTGGTTCTGGTGGC')[0])

ref_y['Insert Sequence'].isin(dat_filtered['sgRNA_trimmed']).sum()/ref_y['Insert Sequence'].shape[0]

0.9907692307692307

### blib

In [142]:
DATADIR = "${KSI_DATA_ROOT}/sequencing_data_1204/00_fastq/"
filename = 'bliballvariant.count.txt'
dat = pd.read_csv(os.path.join(DATADIR,filename),sep = '\t')

In [143]:
dat_filtered = dat.loc[dat['sgRNA'].apply(lambda s: 'CGTACG' in s)]

In [144]:
dat_filtered = dat_filtered.loc[dat_filtered['sgRNA'].apply(lambda s: 'GCCTAGG' in s)]

In [145]:
dat_filtered.shape[0]/dat.shape[0]

0.7989636253270932

In [146]:
dat_filtered['Gene'] = dat_filtered['sgRNA'].apply(lambda s: s.split('CGTACG')[1].split('CCTAGG')[0])

In [147]:
dat_filtered.head(5)

,sgRNA,Gene,blib1_pre,blib1_mtx,blib2_pre,blib2_mtx,blib3_pre,blib3_mtx,blib5_pre,blib5_mtx
0,CCGGCGCGGAGGGGGGGGGGCCTTGGGCGTACGCTTCATCTCAGCC...,CTTCATCTCAGCCACGTGG,1,0,0,0,0,0,0,0
2,CCGGCGCGGAGGGGGGGGGGCCTTGGGCGTACGCAGTATCGTCGGA...,CAGTATCGTCGGATCAGCG,1,0,0,0,0,0,0,0
3,CCGGCGCGGAGGGGGGGGGGCCTTGGGCGTACGCTTGTTGCAGCCA...,CTTGTTGCAGCCACCTGCG,1,0,0,0,0,0,0,0
6,CCGGCGCGGAGGGGGGGGGGCCTTGGGCGTACGCTGCAAGTACGAT...,CTGCAAGTACGATTCTATG,1,0,0,0,0,0,0,0
21,CCGGCTCGTAGGGGGTGGGGCATTGTGCGTACGAAACCCGGGTATC...,AAACCCGGGTATCGCTCAG,1,0,0,0,0,0,0,0

In [148]:
dat_filtered.to_csv('${KSI_DATA_ROOT}/processed_count_table/bliballvariant.count.txt',sep = '\t',index = False)

In [269]:
dat_filtered = pd.read_csv('${KSI_DATA_ROOT}/processed_count_table/bliballvariant.count.txt',sep = '\t')

In [281]:
dat_filtered_sub = dat_filtered.loc[:,['sgRNA','Gene','blib1_pre','blib1_mtx']]
dat_filtered_sub = dat_filtered_sub.loc[dat_filtered_sub.iloc[:,2]+dat_filtered_sub.iloc[:,3]>100,:]
dat_filtered_sub = dat_filtered_sub.loc[~dat_filtered_sub.loc[:,'Gene'].isna(),:]
print(dat_filtered_sub.shape) 
dat_filtered_sub.to_csv('${KSI_DATA_ROOT}/processed_count_table/bliballvariantblib1.count.txt',sep = '\t',index = False)

(77245, 4)

In [282]:
# dat_filtered = pd.read_csv('${KSI_DATA_ROOT}/processed_count_table/bliballvariant.count.txt',sep = '\t')
dat_filtered_sub = dat_filtered.loc[:,['sgRNA','Gene','blib2_pre','blib2_mtx']]
dat_filtered_sub = dat_filtered_sub.loc[dat_filtered_sub.iloc[:,2]+dat_filtered_sub.iloc[:,3]>100,:]
dat_filtered_sub = dat_filtered_sub.loc[~dat_filtered_sub.loc[:,'Gene'].isna(),:]
print(dat_filtered_sub.shape) 
dat_filtered_sub.to_csv('${KSI_DATA_ROOT}/processed_count_table/bliballvariantblib2.count.txt',sep = '\t',index = False)

(102928, 4)

In [283]:
# dat_filtered = pd.read_csv('${KSI_DATA_ROOT}/processed_count_table/bliballvariant.count.txt',sep = '\t')
dat_filtered_sub = dat_filtered.loc[:,['sgRNA','Gene','blib3_pre','blib3_mtx']]
dat_filtered_sub = dat_filtered_sub.loc[dat_filtered_sub.iloc[:,2]+dat_filtered_sub.iloc[:,3]>100,:]
dat_filtered_sub = dat_filtered_sub.loc[~dat_filtered_sub.loc[:,'Gene'].isna(),:]
print(dat_filtered_sub.shape) 
dat_filtered_sub.to_csv('${KSI_DATA_ROOT}/processed_count_table/bliballvariantblib3.count.txt',sep = '\t',index = False)

(82611, 4)

In [284]:
# dat_filtered = pd.read_csv('${KSI_DATA_ROOT}/processed_count_table/bliballvariant.count.txt',sep = '\t')
dat_filtered_sub = dat_filtered.loc[:,['sgRNA','Gene','blib5_pre','blib5_mtx']]
dat_filtered_sub = dat_filtered_sub.loc[dat_filtered_sub.iloc[:,2]+dat_filtered_sub.iloc[:,3]>100,:]
dat_filtered_sub = dat_filtered_sub.loc[~dat_filtered_sub.loc[:,'Gene'].isna(),:]
print(dat_filtered_sub.shape) 
dat_filtered_sub.to_csv('${KSI_DATA_ROOT}/processed_count_table/bliballvariantblib5.count.txt',sep = '\t',index = False)

(177501, 4)

### blib - Batch 2

In [61]:
DATADIR = "${DATA_MOUNT}/sequencing_data_240424/00_fastq//"
filename = 'bliballvariant.count.txt'
dat = pd.read_csv(os.path.join(DATADIR,filename),sep = '\t')

In [62]:
dat_filtered = dat.loc[dat['sgRNA'].apply(lambda s: 'CGTACG' in s)]

In [63]:
dat_filtered = dat_filtered.loc[dat_filtered['sgRNA'].apply(lambda s: 'GCCTAGG' in s)]

In [64]:
dat_filtered.shape[0]/dat.shape[0]

0.7511317112320157

In [65]:
dat_filtered['Gene'] = dat_filtered['sgRNA'].apply(lambda s: s.split('CGTACG')[1].split('CCTAGG')[0])

In [66]:
dat_filtered.head(5)

,sgRNA,Gene,blib1_pre,blib2_pre,blib3_pre,blib1_mtx,blib2_mtx,blib3_mtx
0,CCGGCGCGGCGGTGGTGGGGCCGGGTGCGTACGCTACCGCAAGGGC...,CTACCGCAAGGGCCCTCGG,1,0,0,0,0,0
1,CCGGCGCGGCGGTGGTGGGGCCGGGTGCGTACGCAATCCTATACGC...,CAATCCTATACGCTGTGGG,1,0,0,0,0,0
4,CCGGCGCGGCGGTGGTGGGGCCGGGTGCGTACGCCCCAAACGGATT...,CCCCAAACGGATTAGGGCG,1,0,0,0,0,0
5,CCGGCGCGGCGGTGGTGGGGCCGGGTGCGTACGCCGTATGGCGGCC...,CCGTATGGCGGCCGGGCCG,1,0,0,0,0,0
6,CCGGCGCGGCGGTGGTGGGGCCGGGTGCGTACGCAGTTGGGCTGGA...,CAGTTGGGCTGGACGCCCG,1,0,0,0,0,0

In [67]:
dat_filtered.to_csv('${DATA_MOUNT}/processed_count_table/bliballvariant2.count.txt',sep = '\t',index = False)

In [68]:
dat_filtered = pd.read_csv('${DATA_MOUNT}/processed_count_table/bliballvariant2.count.txt',sep = '\t')

In [76]:
dat_filtered['blib1_mtx'].sum()

53940983

In [70]:
dat_filtered_sub = dat_filtered.loc[:,['sgRNA','Gene','blib1_pre','blib1_mtx']]
dat_filtered_sub = dat_filtered_sub.loc[dat_filtered_sub.iloc[:,2]+dat_filtered_sub.iloc[:,3]>100,:]
dat_filtered_sub = dat_filtered_sub.loc[~dat_filtered_sub.loc[:,'Gene'].isna(),:]
print(dat_filtered_sub.shape) 
dat_filtered_sub.to_csv('${DATA_MOUNT}/processed_count_table/bliballvariant2blib1.count.txt',sep = '\t',index = False)

(123974, 4)

In [71]:
# dat_filtered = pd.read_csv('${KSI_DATA_ROOT}/processed_count_table/bliballvariant.count.txt',sep = '\t')
dat_filtered_sub = dat_filtered.loc[:,['sgRNA','Gene','blib2_pre','blib2_mtx']]
dat_filtered_sub = dat_filtered_sub.loc[dat_filtered_sub.iloc[:,2]+dat_filtered_sub.iloc[:,3]>100,:]
dat_filtered_sub = dat_filtered_sub.loc[~dat_filtered_sub.loc[:,'Gene'].isna(),:]
print(dat_filtered_sub.shape) 
dat_filtered_sub.to_csv('${DATA_MOUNT}/processed_count_table/bliballvariant2blib2.count.txt',sep = '\t',index = False)

(130368, 4)

In [72]:
# dat_filtered = pd.read_csv('${KSI_DATA_ROOT}/processed_count_table/bliballvariant.count.txt',sep = '\t')
dat_filtered_sub = dat_filtered.loc[:,['sgRNA','Gene','blib3_pre','blib3_mtx']]
dat_filtered_sub = dat_filtered_sub.loc[dat_filtered_sub.iloc[:,2]+dat_filtered_sub.iloc[:,3]>100,:]
dat_filtered_sub = dat_filtered_sub.loc[~dat_filtered_sub.loc[:,'Gene'].isna(),:]
print(dat_filtered_sub.shape) 
dat_filtered_sub.to_csv('${DATA_MOUNT}/processed_count_table/bliballvariant2blib3.count.txt',sep = '\t',index = False)

(122563, 4)

### 240425: TODO: run this code chunk after the new blib5 submission is back

In [24]:
dat_filtered = pd.read_csv('${KSI_DATA_ROOT}/processed_count_table/bliballvariant.count.txt',sep = '\t')
dat_filtered_sub = dat_filtered.loc[:,['sgRNA','Gene','blib5_pre','blib5_mtx']]
dat_filtered_sub = dat_filtered_sub.loc[dat_filtered_sub.iloc[:,2]+dat_filtered_sub.iloc[:,3]>100,:]
dat_filtered_sub = dat_filtered_sub.loc[~dat_filtered_sub.loc[:,'Gene'].isna(),:]
print(dat_filtered_sub.shape) 
dat_filtered_sub.to_csv('${DATA_MOUNT}/processed_count_table/bliballvariant2blib5.count.txt',sep = '\t',index = False)

### Merge two batches of results

In [77]:
lib_id = 'blib1'
dat1 = pd.read_csv('${DATA_MOUNT}/processed_count_table/bliballvariant' +lib_id +'.count.txt',sep = '\t')
dat2 = pd.read_csv('${DATA_MOUNT}/processed_count_table/bliballvariant2' +lib_id +'.count.txt',sep = '\t')
dat1.columns = ['sgRNA','Gene',lib_id + '_pre_1',lib_id + '_mtx_1']
dat2.columns = ['sgRNA','Gene',lib_id + '_pre_2',lib_id + '_mtx_2']
dat12 = pd.merge(dat1,dat2,on = ['Gene','sgRNA'])
dat12.to_csv('${DATA_MOUNT}/processed_count_table/bliballvariant12' +lib_id +'.count.txt',sep = '\t',index = False)

In [78]:
lib_id = 'blib2'
dat1 = pd.read_csv('${DATA_MOUNT}/processed_count_table/bliballvariant' +lib_id +'.count.txt',sep = '\t')
dat2 = pd.read_csv('${DATA_MOUNT}/processed_count_table/bliballvariant2' +lib_id +'.count.txt',sep = '\t')
dat1.columns = ['sgRNA','Gene',lib_id + '_pre_1',lib_id + '_mtx_1']
dat2.columns = ['sgRNA','Gene',lib_id + '_pre_2',lib_id + '_mtx_2']
dat12 = pd.merge(dat1,dat2,on = ['Gene','sgRNA'])
dat12.to_csv('${DATA_MOUNT}/processed_count_table/bliballvariant12' +lib_id +'.count.txt',sep = '\t',index = False)

In [79]:
lib_id = 'blib3'
dat1 = pd.read_csv('${DATA_MOUNT}/processed_count_table/bliballvariant' +lib_id +'.count.txt',sep = '\t')
dat2 = pd.read_csv('${DATA_MOUNT}/processed_count_table/bliballvariant2' +lib_id +'.count.txt',sep = '\t')
dat1.columns = ['sgRNA','Gene',lib_id + '_pre_1',lib_id + '_mtx_1']
dat2.columns = ['sgRNA','Gene',lib_id + '_pre_2',lib_id + '_mtx_2']
dat12 = pd.merge(dat1,dat2,on = ['Gene','sgRNA'])
dat12.to_csv('${DATA_MOUNT}/processed_count_table/bliballvariant12' +lib_id +'.count.txt',sep = '\t',index = False)

### blib5 batch2

In [89]:
DATADIR = "${DATA_MOUNT}/sequencing_data_240508/00_fastq//"
filename = 'blib_fp_b2.count.txt'
dat = pd.read_csv(os.path.join(DATADIR,filename),sep = '\t')

In [90]:
dat_filtered = dat.loc[dat['sgRNA'].apply(lambda s: 'CGTACG' in s)]

In [91]:
dat_filtered = dat_filtered.loc[dat_filtered['sgRNA'].apply(lambda s: 'GCCTAGG' in s)]

In [92]:
dat_filtered.shape[0]/dat.shape[0]

0.570939690867996

In [93]:
dat_filtered['Gene'] = dat_filtered['sgRNA'].apply(lambda s: s.split('CGTACG')[1].split('CCTAGG')[0])

In [94]:
dat_filtered.head(5)

,sgRNA,Gene,blib5_pre,blib5_mtx,blib7_pre,blib7_mtx,blib10_pre,blib10_mtx
0,CAGGCTCGTATGTTGTGTGGAATTGTGCGTACGAGACAGTAGGGCT...,AGACAGTAGGGCTAACCAG,1,0,0,0,0,0
1,CAGGCTCGTATGTTGTGTGGAATTGTGCGTACGAAGGAAACCGAAA...,AAGGAAACCGAAATCCGGG,2,0,0,0,0,0
2,CAGGCTCGTATGTTGTGTGGAATTGTGCGTACGAGTAGCTCCGATT...,AGTAGCTCCGATTAACAGG,1,0,0,0,0,0
3,CAGGCTCGTATGTTGTGTGGAATTGTGCGTACGACGGTAAGAGGGT...,ACGGTAAGAGGGTGCTTCG,1,0,0,0,0,0
4,CAGGCTCGTATGTTGTGTGGAATTGTGCGTACGACGGTTATAGTAT...,ACGGTTATAGTATTATCTG,1,0,0,0,0,0

In [95]:
dat_filtered_sub = dat_filtered.loc[:,['sgRNA','Gene','blib5_pre','blib5_mtx']]
dat_filtered_sub = dat_filtered_sub.loc[dat_filtered_sub.iloc[:,2]+dat_filtered_sub.iloc[:,3]>100,:]
dat_filtered_sub = dat_filtered_sub.loc[~dat_filtered_sub.loc[:,'Gene'].isna(),:]
print(dat_filtered_sub.shape) 
dat_filtered_sub.to_csv('${DATA_MOUNT}/processed_count_table/bliballvariant2blib5.count.txt',sep = '\t',index = False)

(144183, 4)

### blib_fp batch 2

In [115]:
DATADIR = "${DATA_MOUNT}/sequencing_data_240508/00_fastq//"
filename = 'blib_fp_b2.count.txt'
dat = pd.read_csv(os.path.join(DATADIR,filename),sep = '\t')

In [116]:
dat_filtered = dat.loc[dat['sgRNA'].apply(lambda s: len(s.split('GGGAGGTGGAGCTAGC'))>1),:]

In [117]:
dat_filtered = dat_filtered.loc[dat_filtered['sgRNA'].apply(lambda s: len(s.split('TGGATCAGGTGGTTAGAAGCTTATTAGTT'))>1),:]

In [118]:
dat_filtered['sgRNA_trimmed'] = dat_filtered['sgRNA'].apply(lambda s: s.split('GGGAGGTGGAGCTAGC')[1].split('GGTGGATCAGGTGGTTAGAAGCTTATTAGTT')[0])

In [119]:
dat_filtered.loc[dat_filtered['sgRNA_trimmed'].apply(lambda s: len(s)==45)].shape[0]/dat_filtered.shape[0]

0.857308007948439

In [120]:
dat_filtered = dat_filtered.loc[dat_filtered['sgRNA_trimmed'].apply(lambda s: len(s)==45)]
dat_filtered['Gene'] = dat_filtered['sgRNA_trimmed'].apply(lambda s: str(Seq(s).translate()))

In [121]:
dat_filtered.head(5)

,sgRNA,Gene,blib5_pre,blib5_mtx,blib7_pre,blib7_mtx,blib10_pre,blib10_mtx,sgRNA_trimmed
1618496,GGGAGGTGGAGCTAGCAGGCAAAATGGTTCTAACGATTCCGATAGA...,RQNGSNDSDRYSDND,1,0,11383,19370,0,0,AGGCAAAATGGTTCTAACGATTCCGATAGATATTCAGATAATGAC
2181121,GGGAGGTGGAGCTAGCAGTAAAGTTAGAGGACCTGTATCAGGTTCT...,SKVRGPVSGSPDSMN,1,0,13375,18484,0,1,AGTAAAGTTAGAGGACCTGTATCAGGTTCTCCAGATTCCATGAAT
2235189,GGGAGGTGGAGCTAGCCAGGCTCAAAAGTTGGTTTCTTCACATAAA...,QAQKLVSSHKPVQNQ,3,0,13999,30921,0,0,CAGGCTCAAAAGTTGGTTTCTTCACATAAACCAGTCCAAAATCAA
2681454,GGGAGGTGGAGCTAGCCCATCCGAAGATTATGAGCATTCACAGTCT...,PSEDYEHSQSPAEQA,1,0,23268,65659,2,1,CCATCCGAAGATTATGAGCATTCACAGTCTCCTGCAGAACAAGCT
2889646,GGGAGGTGGAGCTAGCGAAAAAGCAAGAGAAAAGTTTTATGAGGCT...,EKAREKFYEAKLQQQ,1,0,0,2,0,0,GAAAAAGCAAGAGAAAAGTTTTATGAGGCTAAATTGCAACAGCAA

In [122]:
dat_filtered.to_csv('${DATA_MOUNT}/processed_count_table/blib_fp_b2.count.txt',sep = '\t',index = False)

In [123]:
dat_filtered = pd.read_csv('${DATA_MOUNT}/processed_count_table/blib_fp_b2.count.txt',sep = '\t')
dat_filtered_sub = dat_filtered.loc[:,['sgRNA','Gene','blib10_pre','blib10_mtx']]
dat_filtered_sub = dat_filtered_sub.loc[dat_filtered_sub.iloc[:,2]+dat_filtered_sub.iloc[:,3]>100,:]
print(dat_filtered_sub.shape) 
dat_filtered_sub.to_csv('${DATA_MOUNT}/processed_count_table/blib_fpb2blib10.count.txt',sep = '\t',index = False)

(2844, 4)

In [124]:
dat_filtered = pd.read_csv('${DATA_MOUNT}/processed_count_table/blib_fp_b2.count.txt',sep = '\t')
dat_filtered_sub = dat_filtered.loc[:,['sgRNA','Gene','blib7_pre','blib7_mtx']]
dat_filtered_sub = dat_filtered_sub.loc[dat_filtered_sub.iloc[:,2]+dat_filtered_sub.iloc[:,3]>100,:]
print(dat_filtered_sub.shape) 
dat_filtered_sub.to_csv('${DATA_MOUNT}/processed_count_table/blib_fpb2blib7.count.txt',sep = '\t',index = False)

(3850, 4)

## Merge two batches of results

In [77]:
lib_id = 'blib1'
dat1 = pd.read_csv('${DATA_MOUNT}/processed_count_table/bliballvariant' +lib_id +'.count.txt',sep = '\t')
dat2 = pd.read_csv('${DATA_MOUNT}/processed_count_table/bliballvariant2' +lib_id +'.count.txt',sep = '\t')
dat1.columns = ['sgRNA','Gene',lib_id + '_pre_1',lib_id + '_mtx_1']
dat2.columns = ['sgRNA','Gene',lib_id + '_pre_2',lib_id + '_mtx_2']
dat12 = pd.merge(dat1,dat2,on = ['Gene','sgRNA'])
dat12.to_csv('${DATA_MOUNT}/processed_count_table/bliballvariant12' +lib_id +'.count.txt',sep = '\t',index = False)

In [78]:
lib_id = 'blib2'
dat1 = pd.read_csv('${DATA_MOUNT}/processed_count_table/bliballvariant' +lib_id +'.count.txt',sep = '\t')
dat2 = pd.read_csv('${DATA_MOUNT}/processed_count_table/bliballvariant2' +lib_id +'.count.txt',sep = '\t')
dat1.columns = ['sgRNA','Gene',lib_id + '_pre_1',lib_id + '_mtx_1']
dat2.columns = ['sgRNA','Gene',lib_id + '_pre_2',lib_id + '_mtx_2']
dat12 = pd.merge(dat1,dat2,on = ['Gene','sgRNA'])
dat12.to_csv('${DATA_MOUNT}/processed_count_table/bliballvariant12' +lib_id +'.count.txt',sep = '\t',index = False)

In [79]:
lib_id = 'blib3'
dat1 = pd.read_csv('${DATA_MOUNT}/processed_count_table/bliballvariant' +lib_id +'.count.txt',sep = '\t')
dat2 = pd.read_csv('${DATA_MOUNT}/processed_count_table/bliballvariant2' +lib_id +'.count.txt',sep = '\t')
dat1.columns = ['sgRNA','Gene',lib_id + '_pre_1',lib_id + '_mtx_1']
dat2.columns = ['sgRNA','Gene',lib_id + '_pre_2',lib_id + '_mtx_2']
dat12 = pd.merge(dat1,dat2,on = ['Gene','sgRNA'])
dat12.to_csv('${DATA_MOUNT}/processed_count_table/bliballvariant12' +lib_id +'.count.txt',sep = '\t',index = False)

In [97]:
lib_id = 'blib5'
dat1 = pd.read_csv('${DATA_MOUNT}/processed_count_table/bliballvariant' +lib_id +'.count.txt',sep = '\t')
dat2 = pd.read_csv('${DATA_MOUNT}/processed_count_table/bliballvariant2' +lib_id +'.count.txt',sep = '\t')
dat1.columns = ['sgRNA','Gene',lib_id + '_pre_1',lib_id + '_mtx_1']
dat2.columns = ['sgRNA','Gene',lib_id + '_pre_2',lib_id + '_mtx_2']
dat12 = pd.merge(dat1,dat2,on = ['Gene','sgRNA'])
dat12.to_csv('${DATA_MOUNT}/processed_count_table/bliballvariant12' +lib_id +'.count.txt',sep = '\t',index = False)

In [4]:
lib_id = 'blib7'
dat1 = pd.read_csv('${DATA_MOUNT}/processed_count_table/blib_fp' +lib_id +'.count.txt',sep = '\t')
dat2 = pd.read_csv('${DATA_MOUNT}/processed_count_table/blib_fpb2' +lib_id +'.count.txt',sep = '\t')
dat1.columns = ['sgRNA','Gene',lib_id + '_pre_1',lib_id + '_mtx_1']
dat2.columns = ['sgRNA','Gene',lib_id + '_pre_2',lib_id + '_mtx_2']
dat12 = pd.merge(dat1,dat2,on = ['Gene','sgRNA'])
dat12.to_csv('${DATA_MOUNT}/processed_count_table/blib_fpb12' +lib_id +'.count.txt',sep = '\t',index = False)

In [5]:
lib_id = 'blib10'
dat1 = pd.read_csv('${DATA_MOUNT}/processed_count_table/blib_fp' +lib_id +'.count.txt',sep = '\t')
dat2 = pd.read_csv('${DATA_MOUNT}/processed_count_table/blib_fpb2' +lib_id +'.count.txt',sep = '\t')
dat1.columns = ['sgRNA','Gene',lib_id + '_pre_1',lib_id + '_mtx_1']
dat2.columns = ['sgRNA','Gene',lib_id + '_pre_2',lib_id + '_mtx_2']
dat12 = pd.merge(dat1,dat2,on = ['Gene','sgRNA'])
dat12.to_csv('${DATA_MOUNT}/processed_count_table/blib_fpb12' +lib_id +'.count.txt',sep = '\t',index = False)

In [8]:
dat12

,sgRNA,Gene,blib10_pre_1,blib10_mtx_1,blib10_pre_2,blib10_mtx_2
0,GGGAGGTGGAGCTAGCAACTTGGCTTCTAGTCATACTTATGATAAT...,NLASSHTYDNFHSNS,28746,31599,31187,7622
1,GGGAGGTGGAGCTAGCTTGCCACAAGATAAAGAGTACTATAAGGTT...,LPQDKEYYKVKEPGE,9456,13056,17428,3596
2,GGGAGGTGGAGCTAGCATTTCTGGAACTCAACCAGTTTATCATCAA...,ISGTQPVYHQGEHYQ,12289,15064,15774,3627
3,GGGAGGTGGAGCTAGCGATTATGGAATGATGTCTGACTACGGTACA...,DYGMMSDYGTARRTG,11224,6651,4730,2529
4,GGGAGGTGGAGCTAGCCAGGAAGAAGAGGATGACGATTACCCAGGT...,QEEEDDDYPGSYSPQ,18122,50360,44014,6593
...,...,...,...,...,...,...
2316,GGGAGGTGGAGCTAGCCTTAATAACCTATTGTTTCTATATGATACT...,LNNLLFLYDTHQNLR,779,100,175,254
2317,GGGAGGTGGAGCTAGCAGAGCTGGCGGTGGAAGGACATATCAATCT...,RAGGGRTYQSTVEAY,128,18,65,44
2318,GGGAGGTGGAGCTAGCCCAAAAAGACATACTGTTTTGTATATTTCT...,PKRHTVLYISPLPED,122,30,192,118
2319,GGGAGGTGGAGCTAGCATGGCTTTTCCAGGTCATTTGTATGATGAA...,MAFPGHLYDEVERLY,119,106,410,109
2320,GGGAGGTGGAGCTAGCAAAATTTGGCATCACACTTTTTATAATGAA...,KIWHHTFYNELRLAP,334,15,83,33