In [1]:
import pandas as pd

In [20]:
human_yeast_pos = pd.read_pickle("../../data/training_data/mif_training_230628/test_humanyeast.pkl")

In [7]:
all_neg = pd.read_pickle("../../data/training_data/mif_training_230628/train_nodark.pkl")

In [8]:
all_neg = all_neg.loc[all_neg["label"]==0,:]

In [12]:
yeast_all_neg = all_neg.loc[all_neg["kinase"].isin(human_yeast_pos["kinase"].drop_duplicates()),:]

In [14]:
yeast_all_neg.groupby("kinase").count()

,substrate,substrate_seq,kinase_seq,p_ind,p_aa,kinase_coord,label,kinase_mif,kinase_mif_seq,substrate_mif,substrate_mif_seq
kinase,,,,,,,,,,,
P06241,362,362,362,362,362,362,362,362,362,362,362
P07332,19,19,19,19,19,19,19,19,19,19,19
P07947,36,36,36,36,36,36,36,36,36,36,36
P07948,228,228,228,228,228,228,228,228,228,228,228
P08631,56,56,56,56,56,56,56,56,56,56,56
P09769,31,31,31,31,31,31,31,31,31,31,31
P12931,1044,1044,1044,1044,1044,1044,1044,1044,1044,1044,1044
P16591,36,36,36,36,36,36,36,36,36,36,36
P42684,45,45,45,45,45,45,45,45,45,45,45
P42685,4,4,4,4,4,4,4,4,4,4,4
P43405,143,143,143,143,143,143,143,143,143,143,143
P51451,13,13,13,13,13,13,13,13,13,13,13
P51813,29,29,29,29,29,29,29,29,29,29,29
Q05397,49,49,49,49,49,49,49,49,49,49,49
Q9H3Y6,4,4,4,4,4,4,4,4,4,4,4

In [18]:
neg_rows = []
for i in range(human_yeast_pos.shape[0]):
    curr_row = human_yeast_pos.iloc[i,:]
    curr_kin = curr_row["kinase"]
    print(curr_kin)
    try:
        neg_sel = all_neg.loc[all_neg["kinase"]==curr_kin,:].sample(1)
        neg_rows.append(neg_sel)
    except:
        continue

P42684
P51451
P09769
P42685
P42685
P08631
P08631
Q13470
P42684
P42684
P43405
P42684
P42684
P42684
P51451
P51451
P09769
P09769
P09769
P42685
P42685
P08631
Q13470
P16591
P16591
P16591
P06241
Q05397
Q05397
P12931
P07947
P07947
P42684
P09769
P42685
P16591
P42684
P51451
P42685
P42685
P08631
Q13470
P43405
P43405
P07947
P07947
P07948
P42684
P42684
P51451
P09769
P08631
Q13470
Q13470
P16591
P06241
Q05397
Q05397
P12931
P07947
P51813
P42684
P09769
P09769
P42685
P08631
Q13470
Q13470
P06241
P06241
Q05397
P42684
P42684
P42684
P42684
P42684
P51451
P09769
P42685
P42685
P08631
Q13470
P16591
P06241
Q05397
P42684
P42684
P42684
P51451
P09769
P08631
P07948
P42684
P42684
P51451
P51451
P09769
P42685
P42685
P08631
P16591
P16591
P06241
P07947
P07332
P42684
P09769
P42684
P06241
P42684
P42684
P51451
P09769
P08631
Q13470
Q13470
P16591
P06241
Q05397
P12931
P07947
P07948
P42684
P51813
P42684
P42685
Q13470
Q05397
P42684
P42684
P42684
P51451
P09769
P08631
P12931
P07947
P42684
P43405
P06241
P07948
P51813
P42684
P51451
P09769
P09769
P42685
P08631
P08631
Q13470
Q13470
Q13470
P43405
P16591
P16591
P06241
P06241
P06241
Q05397
Q05397
P12931
P07947
P07948
P07332
P07332
P07332
P42684
P51451
P09769
P08631
Q13470
P06241
P12931
P07947
P42684
P09769
P42685
P08631
P16591
P06241
P07947
P07948
P51813
P51813
P42684
P51451
P51451
P08631
Q13470
P07947
P07948
P07948
P51813
P42684
P42684
P51813
P42684
P51451
P42685
P06241
P12931
P07947
P07948
P51813
P42684
P42684
P42684
P09769
P42684
P42684
P09769
P09769
P42685
P08631
Q13470
P16591
P16591
P16591
P07948
P51813
P42684
P42684
P51451
P09769
P09769
P09769
P42685
P08631
Q13470
P16591
P06241
P12931
P07947
P07947
P42684
P51451
P51451
P09769
P08631
Q13470
P06241
P12931
P07947
P07948
P51813
P42684
P06241
P07948
P42684
Q13470
P42684
P42685
P42684
P51451
P09769
P09769
P42685
Q13470
P06241
P06241
P07948
P51813
P07332
P42684
P09769
P08631
Q13470
P06241
Q05397
P42684
P42684
P51451
P09769
P09769
P08631
P16591
P06241
P07947
P42684
P09769
P09769
P42685
P08631
P08631
Q13470
P16591
P16591
P06241
P07947
P42684
P09769
P42685
P08631
P16591
P06241
P12931
Q9H3Y6
P42684
P51451
P42685
P08631
Q13470
Q13470
P43405
P16591
Q05397
P07947
P07948
P07332
P07332
P42684
P06241
P42684
P51451
P09769
P42685
P43405
P06241
P07947
P07947
P07948
P07948
P51813
P51813
P07332
P07332
P42684
P42684
P42684
P51451
P09769
P09769
P42685
P16591
P16591
P06241
Q9H3Y6
P42684
P06241
P42684
P09769
P42685
P42685
P08631
P08631
P16591
P42684
P42684
P51451
P51451
P09769
P09769
P09769
P08631
P08631
P08631
Q13470
P16591
P16591
P16591
P06241
P06241
P12931
P12931
P07947
P07947
P07947
P42684
P42684
P09769
Q13470
Q05397
P42684
P06241
P42684
P09769
P09769
Q13470
P16591
P06241
Q05397
P07947
P42684
P09769
P09769
P09769
P42685
Q13470
Q13470
P16591
P16591
P16591
P06241
P07947
Q9H3Y6
Q9H3Y6
P42684
P51451
P09769
P08631
Q13470
Q13470
P16591
Q05397
P12931
P07947
P51813
P42684
P42684
P42684
P42684
P51451
P09769
P09769
P09769
P42685
P42685
P42685
P42685
P08631
Q13470
Q13470
Q13470
Q13470
P43405
P16591
P16591
Q05397
Q05397
Q05397
P12931
P07947
P07332
P07332
Q9H3Y6
Q9H3Y6
P42684
P51451
P09769
P08631
Q13470
P16591
P06241
P12931
P07947
P07948
P51813
P42684
P42685
P42684
P08631
P42684
P09769
P09769
P42685
P08631
P08631
Q13470
P16591
P16591
P16591
P07947
P07947
P07948
P07948
P51813
P51813
P51813
P42684
P42684
P09769
Q13470
P16591
P42684
P42684
P42684
P07332
P42684
P51451
P51451
P42685
P08631
P06241
P12931
P07947
P07948
P07948
P51813
P51813
P42684
P09769
P42684
P09769
P42684
P42684
Q13470
P42684
P42684
Q13470
P06241
P42684
P51451
P07948
P42684
P09769
P16591
P42684
P51451
P51813
P51813
P07332
P07332
P42684
P42684
P42684
P51451
P51451
P51451
P51451
P51451
P09769
P09769
P09769
P42685
P42685
P42685
P42685
P42685
P42685
P08631
P08631
P08631
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
P43405
P43405
P43405
P16591
P16591
P16591
P06241
P06241
Q05397
Q05397
Q05397
Q05397
Q05397
P07947
P07947
P07947
P07948
P51813
P07332
P42684
P42684
P42685
P42685
P08631
P16591
P06241
P07947
P07947
P42684
P07332
P42684
P08631
Q13470
Q05397
P42684
P51451
P06241
P42684
P51451
P09769
P09769
P09769
P42685
P42685
P08631
Q13470
Q13470
Q13470
Q13470
P43405
P16591
P06241
Q05397
P07947
P07948
P42684
P42684
P42684
P51451
P06241
P07948
P42684
P42684
P42684
P09769
P42685
Q13470
P16591
Q05397
P42684
P51451
P09769
P09769
P42685
P42685
P08631
Q13470
P43405
P16591
P16591
P06241
P06241
Q05397
P07948
P51813
P51813
P07332
P07332
P42684
P42684
P51451
P51451
P09769
P09769
P09769
P09769
P42685
P42685
Q13470
Q13470
Q13470
Q13470
P16591
P06241
Q05397
Q05397
Q05397
P07947
P07332
P42684
Q13470
P16591
P42684
P42684
P42684
P42684
P51451
P09769
P09769
P09769
P08631
P08631
P08631
Q13470
Q13470
Q13470
Q13470
Q13470
P43405
P16591
P16591
P06241
Q05397
Q05397
Q05397
Q05397
P12931
P07947
P07947
P07947
P07947
P07948
P51813
P51813
P07332
Q9H3Y6
P42684
P42684
P51451
P51451
P09769
P09769
P09769
P08631
Q13470
P16591
P06241
P12931
P07947
P42684
P51451
P09769
P09769
P09769
P42685
P08631
Q13470
Q13470
Q13470
P16591
P16591
P06241
P06241
Q05397
Q05397
P12931
P07947
P07332
P42684
P09769
P42685
P42684
P42684
P42684
P51451
Q13470
P43405
P06241
P07948
P51813
P51813
P51813
P07332
P42684
P09769
Q13470
P07947
P42684
P51451
P09769
P08631
P16591
P06241
P07947
P42684
P42684
P42684
P51451
P09769
P09769
P43405
P06241
P07947
P07947
P07948
P51813
P51813
P42684
P42684
P42684
Q13470
Q05397
P42684
P51451
P08631
P06241
P12931
P07947
P07948
P07332
P42684
P09769
P42684
P07948
P51813
P42684
P51451
P09769
P07948
P42684
P51451
P09769
P08631
P07948
P42684
P43405
P06241
P42684
Q13470
Q13470
P06241
P42684
P42684
P51451
Q13470
P06241
P07947
P07948
P42684
P42684
P51451
P09769
P09769
P42685
P43405
P16591
P06241
P06241
P42684
P42685
P42684
P16591
P42684
P51451
P42685
P42684
P51451
P51451
P51451
P09769
P09769
P09769
P09769
P09769
P42685
P42685
P42685
P08631
P08631
P08631
Q13470
Q13470
P16591
P16591
P16591
P16591
P06241
P06241
P06241
Q05397
P12931
P12931
P12931
P07947
P07947
P07947
P07948
P07332
P42684
P09769
P07948
P07948
P42684
P42684
P51451
P09769
P42684
P07947
P42684
P51451
Q13470
P07947
P42684
P51451
P09769
P09769
P42685
P42685
P08631
Q13470
Q13470
Q13470
P43405
P43405
P43405
P43405
P16591
Q05397
Q05397
Q05397
Q05397
P07947
P07948
P51813
P07332
P42684
P51451
P42685
P42685
P42685
P08631
P16591
P06241
P12931
P07948
P42684
P09769
P42685
P08631
P06241
P42684
P42684
P42684
P08631
Q13470
Q13470
P16591
P07947
P42684
Q13470
Q13470
P42684
P51451
P09769
P08631
Q13470
P16591
P06241
P12931
P07947
P07948
P51813
P42684
P51451
P51451
P09769
P08631
P16591
P06241
P06241
P07948
P42684
P42684
P09769
Q13470
P42684
P42684
P51451
P07948
P42684
P51451
P51451
P09769
P08631
P42684
P51451
P42685
P42684
P51451
P42684
P09769
P08631
P07947
P51813
P42684
P42685
Q13470
P16591
P16591
P07947
P42684
P07948
P51813
P42684
P51451
P09769
P06241
P07948
P51813
P42684
P51451
P09769
P09769
P09769
P42685
P08631
P43405
P06241
P12931
P07947
P42684
P51451
P09769
P08631
Q13470
P43405
P07948
P51813
P42684
P51451
P09769
Q13470
Q13470
P06241
P06241
P07948
P42684
P09769
P09769
P09769
P42685
Q13470
Q13470
Q13470
P06241
P06241
P07948
P51813
P07332
P07332
P42684
P51451
P42685
P43405
P06241
P07948
P51813
P42684
P51451
P51451
P09769
P42685
Q13470
P43405
P43405
P16591
P06241
P06241
P12931
P07947
P07948
P07948
P51813
P51813
P07332
P42684
P51451
P51451
P09769
P09769
P42685
Q13470
Q13470
P06241
P07948
P07332
P42684
P51451
P09769
P42685
P08631
Q13470
P12931
P07947
P07948
P51813
Q9H3Y6
P42684
P51451
P09769
P08631
Q13470
Q13470
Q05397
P51813
P42684
P42684
P09769
P42684
P51451
P09769
P08631
Q13470
P16591
P07948
P51813
Q9H3Y6
P42684
P42685
P42684
P51451
P09769
P42685
Q13470
P43405
P07947
P07948
P51813
P42684
P51451
Q13470
Q13470
P06241
P07948
P51813
P42684
P42684
P09769
P09769
P08631
Q13470
Q13470
P43405
P06241
P06241
Q05397
P07947
P07947
P07948
P07948
P42684
P09769
Q13470
P43405
P07948
P42684
P43405
P42684
P42684
P08631
P43405
P07332
P42684
P07947
P07948
P51813
P42684
P42684
P51451
P09769
P42685
Q13470
P06241
Q05397
P07948
P51813
P42684
P42684
P09769
Q13470
P07948
P42684
P06241
P42684
P42684
P09769
P16591
P42684
P09769
P42685
Q13470
P42684
P42684
P51451
P42685
P08631
P06241
P07947
P42684
P42684
P42685
P42685
Q13470
P42684
P42684
P42684
P09769
P16591
Q05397
P07947
P42684
P06241
P51813
P42684
P06241
P42684
Q13470
P42684
P51451
P09769
P07948
P51813
P07332
P42684
P42684
P51451
P09769
P09769
P06241
P06241
P42684
P51451
P42685
Q13470
P43405
Q05397
P07947
P07948
P07332
P42684
P42684
P51451
P51451
P51451
P51451
P51451
P09769
P09769
P09769
P09769
P09769
P09769
P42685
P42685
P08631
P43405
P16591
P06241
P12931
P07947
P07947
P07947
P07948
P07948
P51813
P42684

P42684
P42684
P51451
P51451
P09769
P42685
P43405
P06241
P06241
P12931
P07947
P07948
P42684
P42684
P42684
P42684
P51451
P51813
P42684
P42684
P09769
P42685
P08631
Q13470
P16591
Q05397
Q05397
P07332
P42684
P42684
P51451
P42685
P07948
P51813
P51813
P42684
P42684
P51451
P42685
Q13470
P07948
P51813
P42684
P42684
P09769
P06241
P42684
P42684
P51451
P51451
P51451
P09769
P09769
P09769
P08631
P08631
P08631
P08631
Q13470
Q13470
P16591
P16591
P06241
P12931
P12931
P07947
P07947
P07947
P42684
P07948
P42684
P42684
P09769
P42685
Q13470
Q13470
Q13470
P16591
P16591
Q05397
Q05397
P07947
P07948
P42684
P42684
P51451
P42684
P51451
P09769
P08631
P16591
P06241
P42684
P42685
P42684
P51451
P42685
P42684
P42684
P09769
P06241
P12931
P42684
P42684
P51451
P51451
P06241
P07947
P07948
P51813
P51813
P42684
P42684
Q13470
P42684
P42685
Q13470
P16591
P42684
P42684
P16591
P42684
P42684
P09769
P42685
P08631
Q13470
Q13470
P16591
P42684
P06241
P42684
P51451
P16591
P16591
P12931
P07947
P42684
P51451
P09769
P42685
P08631
Q13470
Q13470
P16591
P06241
P07947
P07948
P51813
P42684
P51451
P09769
P42685
Q13470
P06241
P07947
P07948
P51813
P42684
P42684
P42684
P51451
P08631
P06241
P12931
P07947
P42684
P42684
P51451
P09769
P42684
P42684
P09769
P42685
Q13470
Q13470
Q13470
P43405
P16591
Q05397
Q05397
P42684
P51451
P51451
P09769
P09769
P09769
P09769
P09769
P09769
P09769
P09769
P09769
P09769
P09769
P43405
P07947
P42684
P51451
P42685
Q13470
P16591
P42684
P51451
P16591
P42684
P51451
Q13470
P06241
P07332
P42684
P51451
P09769
P09769
P42685
P08631
P06241
Q05397
P12931
P07947
P51451
P51451
P09769
P08631
P08631
P08631
P16591
P06241
P06241
P07947
P07947
P51451
P09769
P16591
P16591
P06241
P07947
P51813
P51451
P09769
P42685
Q13470
P16591
P06241
Q05397
P12931
P07947
P07332
P51451
P51451
P51451
P09769
P42685
P16591
P06241
P12931
P07947
P07948
P07332
P51451
P42685
P08631
P16591
P06241
P07947
P07332
P51451
P51451
P09769
P09769
P09769
P09769
P42685
P42685
P42685
P08631
P08631
Q13470
Q13470
Q13470
P43405
P43405
P43405
P16591
Q05397
Q05397
Q05397
P12931
P07947
P07947
P07332
P51451
P09769
P09769
P09769
P42685
P42685
P08631
P08631
Q13470
Q13470
P16591
P16591
P06241
P06241
P06241
Q05397
P12931
P12931
P12931
P07947
P07947
P07947
P07948
P07948
P07332
P51451
P09769
P08631
P16591
P06241
P12931
P07947
P51451
P09769
P09769
P42685
P08631
P08631
P43405
P16591
P06241
Q05397
P12931
P07947
P07948
P51451
P09769
P07947
P51451
P09769
P42685
P08631
Q13470
P16591
P07947
P07948
P07332
P51451
P09769
P09769
P51813
P51451
P51451
P09769
P09769
P08631
P08631
P06241
P06241
P12931
P12931
P07947
P07947
P07948
P07948
P07332
P07332
P51451
P09769
P09769
Q13470
P06241
P07332
P51451
P51451
Q13470
P51451
P42685
P16591
P51451
P07947
P51451
P08631
P06241
P12931
P07947
P51451
P09769
P08631
P06241
P51451
Q13470
P16591
Q05397
P07332
P51451
P51451
P09769
P07947
P07948
P51451
P09769
P42685
P08631
Q13470
P16591
P06241
P12931
P07947
P07948
P51451
P42685
P16591
P12931
P07947
P51451
P09769
P09769
P09769
P42685
P08631
P07947
P07948
P51813
P07332
P51451
P09769
P08631
P16591
P06241
P51451
P09769
P08631
Q13470
P16591
P07947
P51451
P09769
P16591
P51451
P09769
P42685
P08631
Q13470
P16591
P06241
Q05397
P12931
P07947
P51451
P09769
P09769
P09769
P42685
P08631
Q13470
P16591
P16591
P06241
Q05397
P12931
P07947
P07948
P07332
P51451
Q13470
P07947
P51451
P09769
P42685
P08631
Q13470
Q05397
P12931
P07947
P07948
P51451
P09769
P42685
P08631
P16591
P06241
P51451
Q05397
P07947
P07948
P51451
P09769
P09769
P12931
P51451
P42685
P08631
P16591
P06241
P07947
P51451
P09769
P42685
P08631
P08631
Q13470
P43405
P06241
Q05397
P12931
P07947
P51813
P51451
Q13470
P06241
P07947
P07948
P51813
P51813
P51451
P09769
P08631
Q13470
P16591
P16591
P06241
P12931
P07947
P51451
P51451
P08631
P06241
P12931
P07947
P51451
P09769
P08631
P16591
P07948
P51451
P51451
P09769
P42685
P08631
P08631
P06241
P12931
P07947
P07947
P07948
P51451
P09769
P08631
P07947
P51451
P42685
P42685
P42685
P16591
P07332
P51451
P09769
P09769
P09769
P08631
P08631
P12931
P07947
P07947
P51451
P08631
P16591
P51451
Q13470
P51451
P51451
P07948
P51813
P07332
P51451
P09769
P42685
P08631
P16591
P12931
P51451
P09769
P08631
P16591
P12931
P07947
P51451
P51451
P07947
P07948
P51813
P51451
P06241
P07947
P07948
P51451
P09769
P42685
Q13470
Q05397
P51451
P09769
P08631
P06241
P07947
P07948
P51813
P07332
P51451
P08631
P06241
P07948
P07948
P07332
P51451
P43405
P43405
P07948
P51813
P51451
P51451
P42685
P08631
P12931
P07947
P51451
P09769
P09769
P08631
Q13470
P16591
P16591
P07947
P07948
P07332
P51451
P09769
P51813
P51451
P51451
P09769
P42685
P08631
P06241
P12931
P07947
P51451
P09769
P09769
P42685
P42685
P42685
P08631
P08631
Q13470
Q13470
P43405
P16591
P06241
Q05397
Q05397
P12931
P07947
P07947
P51451
Q13470
Q05397
P07947
P07948
P51451
P51451
P09769
P08631
P06241
P51451
P09769
P06241
P12931
P07947
P07948
P51451
P51451
P08631
P43405
P43405
P07948
P51813
P51451
P42685
Q13470
P07948
P51813
P51451
P51451
P08631
P08631
P16591
P16591
P12931
P07947
P51451
P09769
P07948
P51813
P51451
P07948
P51813
P51451
P08631
P51451
Q13470
P07948
P51451
P51451
P07947
P07948
P51813
P51451
P06241
P51451
P51451
P09769
P42685
P08631
Q13470
P06241
P07948
P51813
P07332
P51451
P51451
P09769
P09769
P08631
Q13470
P43405
P06241
P07948
P07332
Q9H3Y6
P51451
P09769
P42685
Q13470
Q13470
P12931
P07947
P07947
P07948
P51451
P09769
P42685
Q13470
P43405
Q05397
P07948
P51813
P07332
P51451
P09769
P42685
Q13470
Q13470
P06241
Q05397
P07948
P07332
Q9H3Y6
P51451
P42685
P08631
P07948
P51451
P07948
P51451
P51451
P09769
P09769
P42685
Q13470
P06241
P06241
P07948
P07948
P51813
P07332
Q9H3Y6
P51451
P08631
P16591
Q05397
P51451
P07948
P51451
P07948
P51813
P51451
P16591
P12931
P07947
P51451
P08631
P07947
P07948
P51813
P51451
P06241
P06241
P12931
P07947
P51451
P51451
P09769
P09769
P08631
P43405
P07947
P07948
P07948
P51813
P07332
P51451
P42685
P16591
Q9H3Y6
P51451
Q13470
P07947
P51451
P09769
P42685
P16591
P06241
Q05397
P07947
P07332
P51451
P51451
P51451
P51451
P09769
P09769
P42685
Q13470
Q13470
Q13470
P43405
Q05397
P07947
P51451
P51813
P51451
P09769
Q13470
P07948
P51451
P07948
P51813
P51451
P51451
Q13470
P06241
P51451
P09769
P42685
Q13470
Q13470
P06241
Q05397
Q05397
P12931
P07947
P07948
P51451
P51451
P09769
P09769
P06241
P07947
P07948
P07948
P51451
P51451
P51451
P09769
P09769
P09769
P42685
P42685
P08631
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
P43405
P43405
P43405
P43405
P16591
P16591
P06241
P06241
P06241
Q05397
P12931
P07947
P07947
P51813
P07332
P51451
P09769
P09769
P42685
P08631
P08631
P08631
P16591
P16591
P06241
P06241
P12931
P07947
P51451
P07948
P51451
P42685
P51451
P08631
Q13470
P07947
P07947
P51451
P09769
P08631
P16591
P12931
P07947
P07947
P51451
P51451
P09769
P08631
P06241
P07947
P51451
P06241
P07947
P07948
P51451
P08631
P16591
P07947
P51451
P51451
P51451
P08631
P07948
P51451
P09769
P51451
P09769
P42685
P08631
P16591
P12931
P07947
P07948
P07332
P51451
P16591
P07947
P09769
Q13470
P51813
P09769
P42685
P08631
P16591
P06241
P51813
P07332
P09769
P06241
P51813
P07332
P09769
P42685
Q13470
Q05397
P07948
P51813
P07332
Q9H3Y6
P09769
P51813
P09769
P42685
Q13470
Q13470
P51813
P51813
P09769
P51813
P09769
P09769
P09769
P08631
P08631
Q13470
P16591
P16591
P06241
P06241
P06241
Q05397
P12931
P07947
P07947
P07947
P09769
P42685
P42685
P16591
P16591
P06241
P07947
P09769
P16591
P06241
P07947
P09769
P16591
P09769
P42685
P42685
P08631
P16591
P16591
P06241
P09769
P08631
P16591
P06241
P07947
P09769
P16591
P09769
Q13470
P16591
Q05397
P09769
Q13470
P16591
P09769
P16591
P06241
P09769
P16591
P09769
P16591
P09769
Q13470
Q13470
P16591
P07947
P09769
P08631
P16591
P12931
P09769
P16591
P09769
P16591
P09769
P16591
P09769
P42685
P16591
P07947
P09769
P42685
P08631
Q13470
P16591
P12931
P07947
P09769
P42685
P08631
P16591
P06241
Q05397
P12931
P07947
P09769
P09769
P16591
P16591
Q05397
P09769
P42685
P42685
Q13470
Q13470
Q13470
Q13470
Q13470
P43405
P43405
P16591
P16591
P16591
Q05397
Q05397
P07332
P09769
P09769
P16591
P09769
P42685
P08631
P16591
P06241
P07947
P09769
P16591
P06241
P09769
P09769
P16591
P09769
P42685
P16591
P09769
P08631
P16591
P06241
P09769
P08631
P16591
P06241
P07332
P09769
Q13470
P43405
P43405
P16591
P07332
P09769
P08631
P16591
P06241
Q05397
Q05397
P09769
P09769
P09769
P42685
P42685
P08631
P08631
P43405
P16591
Q05397
P07947
P09769
P16591
P07947
P07947
P09769
P16591
P09769
P08631
P16591
P06241
Q05397
P12931
P09769
P16591
P09769
P08631
P16591
P06241
P07947
P09769
P42685
Q13470
P43405
P16591
P06241
Q05397
P07948
P07332
P09769
Q13470
P16591
P09769
P16591
P07947
P09769
P09769
P09769
P42685
P08631
Q13470
P16591
P06241
P07947
P09769
P42685
P08631
P06241
Q05397
P07332
Q9H3Y6
P09769
P07948
P07332
P09769
P09769
P09769
P09769
P07947
P07332
P09769
P09769
P42685
Q13470
P43405
Q05397

P07332
Q9H3Y6
P09769
P08631
P09769
P09769
Q13470
P43405
Q05397
P09769
P09769
P09769
P09769
P08631
P06241
P12931
P07947
P09769
Q13470
P09769
P09769
P09769
P08631
P09769
P06241
P09769
P09769
P42685
P09769
P09769
P09769
P09769
P08631
Q13470
P12931
P07947
P09769
P09769
P09769
P42685
P06241
P09769
P08631
P09769
P12931
P07947
P07948
P09769
Q13470
Q13470
P09769
P09769
P08631
P09769
P09769
Q13470
P09769
P06241
P07948
P09769
P07947
P09769
P06241
P09769
P09769
P09769
P07947
P09769
P08631
P08631
P12931
P07947
P09769
P07947
P09769
P06241
P06241
P09769
P09769
P08631
P09769
P09769
P42685
P09769
P43405
P09769
P09769
P09769
P09769
P09769
P09769
P09769
P08631
P09769
Q13470
P09769
P07947
P09769
P09769
Q05397
P09769
P06241
P12931
P09769
P09769
P09769
P09769
P09769
P09769
Q9H3Y6
P09769
P09769
Q13470
P07948
P09769
Q13470
P09769
P08631
Q13470
P06241
P07948
P09769
P09769
P09769
P42685
P09769
Q05397
P09769
P09769
P43405
P09769
Q13470
P09769
P09769
P08631
P12931
P07947
P07947
P09769
P09769
P42685
P07947
P09769
P06241
P09769
P12931
P07947
P07947
P09769
P09769
Q13470
P07948
P09769
P09769
P09769
P06241
P09769
P09769
P08631
P06241
P12931
P07947
P07947
P09769
P42685
P09769
P09769
P42685
P08631
P06241
P06241
P09769
P42685
P08631
Q13470
P07947
P09769
P08631
P06241
P12931
P07947
P09769
P09769
P09769
P42685
P06241
P12931
P09769
P07947
P09769
P09769
P08631
P09769
P09769
P09769
P09769
P09769
P07947
P09769
P09769
P09769
P09769
P09769
P09769
P09769
P08631
P09769
Q13470
P07947
P09769
P09769
P08631
P09769
P07947
P09769
Q13470
P09769
P42685
P42685
Q13470
P43405
P12931
P51813
P42685
P16591
P42685
P08631
P16591
P42685
P08631
P16591
P42685
P16591
P07947
P42685
P42685
P08631
Q13470
P16591
P07947
P42685
P16591
P42685
Q13470
P16591
P06241
P42685
P16591
P42685
P08631
P16591
P42685
P16591
P16591
P42685
P08631
Q13470
P16591
P42685
P42685
P42685
Q13470
P42685
P42685
Q13470
Q13470
P42685
P42685
P07948
P42685
P43405
P42685
P42685
P42685
P08631
P12931
P07947
P07947
P42685
P42685
P42685
P08631
P42685
P12931
P07947
P42685
P42685
P42685
P08631
P06241
P42685
P42685
P42685
P08631
Q13470
P43405
P07947
P42685
Q13470
Q13470
Q13470
Q05397
Q05397
Q05397
P42685
Q13470
P42685
P42685
Q13470
P42685
P42685
P42685
Q05397
P42685
P42685
P42685
Q05397
P42685
P07947
Q9H3Y6
P42685
P42685
P08631
Q13470
P06241
Q05397
P42685
P42685
P42685
P42685
P42685
P07947
P42685
P42685
P42685
P42685
P42685
P42685
P42685
P42685
Q13470
P07947
P42685
P42685
Q13470
P42685
P42685
P08631
P16591
P08631
P16591
P06241
P07332
P08631
Q13470
P16591
P08631
P06241
P12931
P08631
P06241
P08631
P06241
P08631
P07947
P08631
P08631
P08631
P08631
P12931
P08631
P08631
P08631
P08631
P08631
P08631
P08631
P08631
Q13470
P51813
Q13470
P51813
P51813
Q13470
P16591
Q05397
Q13470
P16591
Q13470
P16591
Q13470
P16591
Q13470
P16591
Q13470
P16591
Q13470
P07332
Q13470
P06241
P07948
Q13470
P06241
Q13470
Q13470
P43405
P06241
P06241
P06241
Q13470
Q05397
P07948
Q13470
Q05397
Q13470
Q05397
Q13470
Q05397
Q13470
Q05397
P07947
Q13470
Q05397
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q05397
Q05397
Q05397
Q05397
Q13470
Q05397
Q13470
Q13470
Q05397
Q13470
P43405
Q13470
P43405
Q13470
P43405
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
P07947
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
P07947
Q13470
P07947
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
Q13470
P43405
Q9H3Y6
Q9H3Y6
P43405
P43405
P43405
P43405
P43405
P43405
P43405
P43405
P43405
P43405
P43405
P43405
P43405
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P06241
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P16591
P06241
P07947
P16591
P16591
P16591
P16591
P16591
P06241
P07947
P16591
P16591
P16591
P07332
P16591
P16591
P16591
P16591
P16591
P16591
P06241
P51813
P06241
P07948
P07332
P06241
P07332
P06241
P06241
P07947
P06241
P06241
P06241
P06241
P06241
P06241
P06241
P06241
P06241
P07948
P06241
P06241
P06241
P07947
P06241
P06241
Q05397
P07948
Q05397
Q05397
Q05397
Q05397
Q05397
P12931
P12931
P07947
P12931
P12931
P12931
P12931
P07947
P12931
P12931
P12931
P07947
P12931
P07947
P07947
P07948
P51813
P07947
P07948
P07947
P07947
P07947
P07947
P07947
P07947
P07947
P07947
P07947
P07947
P07947
P07947
P07947
P07947
P07947
P07948
P07948
P07948
P51813
P51813
P51813
P51813
P51813
P51813
P51813
P51813
P51813
P51813
P51813
P51813
P51813
P51813
P07332
P07332
P07332
P07332
P07332
P07332
P07332
P07332
Q9H3Y6
Q9H3Y6
Q9H3Y6
Q9H3Y6
Q9H3Y6

In [19]:
yeast_neg_df = pd.concat(neg_rows,axis = 0)

In [22]:
yeast_1n1p = pd.concat([human_yeast_pos,yeast_neg_df],axis = 0)

In [23]:
yeast_1n1p.groupby("label").count()

,substrate,substrate_seq,kinase,kinase_seq,p_ind,p_aa,kinase_coord,kinase_mif,kinase_mif_seq,substrate_mif,substrate_mif_seq
label,,,,,,,,,,,
0,2806,2806,2806,2806,2806,2806,2806,2806,2806,2806,2806
1,3142,3142,3142,3142,3142,3142,3142,3142,3142,3142,3142

In [24]:
yeast_1n1p.to_pickle("../../data/benchmark_sets/yeast_human_1n1p.pkl")

In [25]:
cp ../../data/training_data/mif_training_230628/test_dark.pkl ../../data/benchmark_sets/test_dark.pkl

In [26]:
cp ../../data/training_data/interations_e2e_1n1p_db_classed_random_lysate_random_withacc_230621_train.pkl ../../data/benchmark_sets/interations_e2e_1n1p_db_classed_random_lysate_random_withacc_230621_train.pkl

In [27]:
cp ../../data/training_data/interations_e2e_1n1p_db_classed_random_lysate_random_withacc_230621_test.pkl ../../data/benchmark_sets/interations_e2e_1n1p_db_classed_random_lysate_random_withacc_230621_test.pkl